name: lcs_new_age
description: A satirical game about American politics.
publish_to: 'none'
version: 1.0.1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  pixel_snap: ^0.1.2
  xml: ^6.3.0
  flutter_svg: ^2.0.7
  collection: ^1.17.2
  format: ^1.3.0
  shared_preferences: ^2.2.2
  json_annotation: ^4.8.1
  file_saver: ^0.2.12
  file_picker: ^6.2.0
  source_map_stack_trace: ^2.1.1
  source_maps: ^0.10.12
  http: ^1.2.1
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  lints: ^3.0.0
  build_runner: ^2.4.8
  json_serializable: ^6.7.1

flutter:
  assets:
   - assets/xml/
   - assets/flags/
   - assets/maps/
   - assets/art/
  uses-material-design: true
  fonts:
   - family: SourceCodePro
     fonts:
      - asset: fonts/SourceCodePro-Regular.ttf
